### PR TITLE
WIP: Import events from OutSavvy

### LINKED ISSUE #2742: [Bug]: OutSavvy calendar events not importing
## Description

The OutSavvy calendar for 'Queer Platonic Coparenting' shows 0 events:

Image

There are four upcoming events listed on the group's [OutSavvy page](https://www.outsavvy.com/event/24577/queer-platonic-coparenting-meet-up-for-prospective-co-parents):

Image

What were you doing?

## Steps to reproduce

1. Logged in to admin.placecal.org
2. Visited Calendars > Queer Platonic Coparenting > View this calendar
3. Saw the calendar had imported successfully, but 0 events are listed
4. Compared to Queer Platonic Coparenting's OutSavvy page, which lists 4 events.

## What you expected to happen

Expected to see 4 events listed for this partner.

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

### PR DESCRIPTION
**Pull request by james-collapse**
Resolves #2742

## Description

This change adds a new OutSavvy-specific parser which:

- Gets upcoming event URLs from the organiser page
- Imports each event using the JSON-LD parser.

### Motivation and Context

It was observed that new events from partners using OutSavvy were not importing (see #2472). On investigation, OutSavvy organiser pages do not contain JSON-LD with event data. They do, however, contain URLs for upcoming events, which can then be queried for JSON-LD event data.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I added tests (under `test/jobs/calendar_importer/outsavvy_parser_test.rb`) to check that:

- URLs in the expected format were pulled from an organiser page with events
- No URLs were pulled for an organiser page with no upcoming events

Note that these tests may fail if the state of either organiser's page changes - for example, if the first organiser no longer has any upcoming events.

I then tested the importer by running the `import_calendar` task for an existing OutSavvy calendar (ID 247). Since the existing calendar is set to use the LD+JSON parser, I forced it to use the 'auto' importer mode for my test.

### How Will This Be Deployed?

Each OutSavvy calendar will need to be set to use the OutSavvy importer mode.

### CODE REVIEW

File: app/jobs/calendar_importer/parsers/outsavvy.rb [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+        response_body = Base.read_http_source(event_url)
+
+        doc = Nokogiri::HTML(response_body)
+        data_nodes = doc.xpath('//script[@type="application/ld+json"]')
+
+        data_nodes.reduce([]) do |out, node|
+          json = Base.safely_parse_json(node.inner_html)
+          expanded = JSON::LD::API.expand(json)
+          compact = JSON::LD::API.compact(expanded, CONTEXT)
+          out.append compact
```
Comment (james-collapse) [inline app/jobs/calendar_importer/parsers/outsavvy.rb:55]: This is copied from `Parsers::LdJson` - do you know how I can refactor this so I'm not repeating myself?

Comment (kimadactyl) [reply app/jobs/calendar_importer/parsers/outsavvy.rb:55]: ahh i see what you mean. ok i think i will need to take a proper look at this as im not sure either! 

i guess the alternate approach is to move the logic into a helper class but im kinda rusty and dont know how to do that

maybe @pedantic-git has an idea more off hand than me?

**Comment by kimadactyl** [comment]
Confirmed working on staging 
image
