### PR TITLE
Fix: partner tag selector bug

### LINKED ISSUE #1460: [Bug]: Create Partner tag selection box
## Description

As an admin creating a new partner, I would like to use the fancy select2 tag selector.

## Steps to reproduce

1. Be logged in as admin
2. Navigate to 'Add new partner page'
3. Scroll to tag selection input

## What you expected to happen

Be able to use fancy tag selector.

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Closes #1460 

On admin partner edit page, partners with missing opening times value would crash JS and cause tags selector to fail.

Quick sanitisation of value and a system test to cover that scenario

### CODE REVIEW

**Review by erbridge — APPROVED** [review]
Just to check I've understood this change:

Before: If a partner had no opening times, this would fall over because `data-opening-times-data-value='<%= opening_times_payload %>'` would evaluate to `data-opening-times-data-value='nil'` or similar.

After: If there are no opening times we default to an empty list, so things don't fall over.

This feels like something that should be the model's responsibility to do. Like the opening times should default to an empty list everywhere, instead of patching it in the view. Did you try this and hit yak shaving territory? If not, could you check if doing that still results in a green test suite instead of implementing a special case here? If it's not simple to do that, this is ok, though.

File: test/system/admin/partner_test.rb [hunk 1]
```diff
@@ -91,4 +91,17 @@ class AdminPartnerTest < ApplicationSystemTestCase
...
+  test 'opening time picker on partner form survives missing value' do
+    @partner.update! opening_times: nil
+
+    click_sidebar 'partners'
+    await_datatables
+    click_link @partner.name
+    await_select2
+
+    # very specific bug here: if opening times has malformed data
+    #   it will crash the partner tags selector
```
Comment (erbridge) [inline test/system/admin/partner_test.rb:104]: Is this referring to a bug that exists in the test, a bug we're testing for, a workaround, what?

Comment (ivan-kocienski-gfsc) [reply test/system/admin/partner_test.rb]: i expanded the comment

**Comment by ivan-kocienski-gfsc** [comment]
I have moved the json sanitisation into the model, which is a much better place for it

**Review by erbridge — APPROVED** [review]
Much nicer! You've disabled parallelization, which might have been an accident? Otherwise, looks good.

File: test/test_helper.rb [hunk 2]
```diff
@@ -32,7 +32,7 @@ module ActiveSupport
   class TestCase
     include FactoryBot::Syntax::Methods
 
-    parallelize(workers: :number_of_processors)
+    # parallelize(workers: :number_of_processors)
```
[the remark this answers is not in the document]
Comment (ivan-kocienski-gfsc) [reply test/test_helper.rb:35]: i did because when i ran the systems test it spun up 4x servers and just killed my computer (i have a lot of stuff open to do all my projects). this then led the tests to have a 50% failure rate because they kept timing out (the socket).
