### PR TITLE
Sanitise and combine strings on iCal event description fields

### LINKED ISSUE #1208: [Bug]: Importer not properly displaying punctuation characters from certain sources
## Description

When viewing issues, certain characters like quote marks (`'`) or dashes (`-`) are replaced with `?` in the description text

## Steps to reproduce

1. View [here](https://trans-dimension.placecal.org/events/277027) and [here](https://trans-dimension.placecal-staging.org/events/277343)
2. I see weird question marks in the description in the first one
3. I see lots of `\n` characters in the second one

Screenshot from 2022-05-03 13-06-29

## What you expected to happen

I should be able to see punctuation instead of question marks, and newlines instead of `\n`

Screenshot from 2022-05-03 13-06-14

Screenshot 2022-05-03 at 17 36 55

### PR DESCRIPTION
**Pull request by ivankocienski**
Fixes #1208

### CODE REVIEW

File: app/jobs/calendar_importer/events/base.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@ def rrule
     end
 
     def sanitize_invalid_char(input)
-      input = I18n.transliterate(input)
+      # input = I18n.transliterate(input)
       input.encode('utf-8', :invalid => :replace, :undef => :replace, :replace => '')
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/events/base.rb:19]: while we're here can we just kill this ancient hash syntax pls :) otherwise looks good!

File: app/jobs/calendar_importer/calendar_importer_task.rb [hunk 2]
```diff
@@ -28,6 +28,11 @@ def run
     all_event_uids = Set.new(calendar.events.upcoming.pluck(:uid))
     active_event_uids = Set.new
 
+    # this can be useful if you want to force import on your local machine
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/calendar_importer_task.rb:31]: can we make this a yarddoc-compatible message so it comes up in the docs when you search the function? this feels like important info basically and we should make it easier to find :)

**Review by kimadactyl — CHANGES_REQUESTED** [review]
couple tiny changes otherwise looks good!

File: app/jobs/calendar_importer/events/base.rb [hunk 3]
```diff
@@ -15,7 +15,7 @@ def rrule
     end
 
     def sanitize_invalid_char(input)
-      input = I18n.transliterate(input)
+      # input = I18n.transliterate(input)
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/events/base.rb:18]: why is this commented out and not deleted?

**Review by kimadactyl — APPROVED** [review]
