### PR TITLE
Importer not logging importer used

### LINKED ISSUE #1261: [Bug]: importer_used is not set properly on calendars
## Description

For a non-ICal importer, we should be setting `importer_used`. 

## Steps to reproduce

1. Run the importer
2. Open the console and type `Calendar.where(importer_used: nil).count`
3. Observe that there are 53 calendars on Staging (And 63 locally?) that do not have `importer_used` set

## What you expected to happen

The `importer_used` field should be set properly for all the calendars we have.

### PR DESCRIPTION
**Pull request by ivankocienski**
Fixes #1261 - calendar importer not changing state correctly if an import has no events

### CODE REVIEW

File: app/jobs/calendar_importer/calendar_importer_task.rb [hunk 1]
```diff
@@ -29,53 +29,54 @@ def run
...
-      # next if parsed_event.is_address_missing?
-
-      active_event_uids << parsed_event.uid
-
-      parsed_event.save_all_occurences
-
-    rescue CalendarImporter::EventResolver::Problem => e
-      notices << e.message
-    end
+    if parsed_events.present?
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/calendar_importer_task.rb:32]: This is a very big method could it be broken up a bit to make it easier to read what's going on? Maybe the big if loop in a helper method?

File: app/jobs/calendar_importer_job.rb [hunk 2]
```diff
@@ -9,6 +9,11 @@ class CalendarImporterJob < ApplicationJob
     report_error exception, "Calendar URL is not accessible"
   end
 
+  rescue_from ActiveRecord::ActiveRecordError do |exception|
+    raise exception if Rails.env.development? && @silence_db_exceptions == false
```
Comment (kimadactyl) [inline app/jobs/calendar_importer_job.rb:13]: Assume you've thought about this but does this not want to activate for env == test too?

File: app/jobs/calendar_importer/calendar_importer_task.rb (hunk 1 above)
Comment (ivankocienski) [reply app/jobs/calendar_importer/calendar_importer_task.rb:32]: I agree it is a touch long but 30% of it is comment explaining the algorithm. Could be moved into helper methods but would that improve parsability? Much of the fiddly logic from the original has been moved into the EventResolver helper class already.

Comment (kimadactyl) [reply app/jobs/calendar_importer/calendar_importer_task.rb:32]: i think the thing that increases parsability is simply having a method named say, "make_events_do_good_thing" so you can then just read the method name and not to get into the weeds. if that makes sense! almost kinda like writing in pseudocode except its not pseudocode?

Comment (kimadactyl) [reply app/jobs/calendar_importer/calendar_importer_task.rb:32]: like yes it might increase the overall LoC but just having a simple human parsable top level method makes it a ton easier to remember whats going on i think

Comment (ivankocienski) [reply app/jobs/calendar_importer/calendar_importer_task.rb:32]: i believe you are describing "self documenting code". i will have a stab at it.

yeah rubocop is way too strict out of the box but its better to be too strict and loosen up than have nothing and add rules (like- otherwise why bother?)
