### PR TITLE
Safely read opening_times from partner

### LINKED ISSUE #1099: Querying a partner for OpeningHours throws error if data has a nil value
**Describe the bug**
Cannt get opening hours data for a Partner with `nil` in them.

**To Reproduce**
1. Using graphiql:
```
query Partner($id: ID!) { 
  partner(id: $id) {
    openingHours {
      dayOfWeek
      opens
      closes
    }
  }
}
```

```
{"id": 17
}
```

**See error**
`"message": "no implicit conversion of nil into String",`

**Expected behavior**
Response json for a partner's opening hours

### PR DESCRIPTION
**Pull request by ivankocienski**
Fixes #1099

### CODE REVIEW

File: test/integration/graphql/partners_integration_test.rb [hunk 1]
```diff
@@ -253,4 +253,29 @@ def check_basic_fields(data, partner)
...
+            opens
+            closes
+            dayOfWeek
+          }
+        }
+      }
+    GRAPHQL
+
+    result = PlaceCalSchema.execute(query_string)
+    assert result.key?('errors') == false, 'errors are present'
```
Comment (alexandria-gfsc) [inline test/integration/graphql/partners_integration_test.rb:274]: I think you can use `refute` here rather than `assert x == false`?

Comment (ivankocienski) [reply test/integration/graphql/partners_integration_test.rb:274]: do you think i should change it?

Comment (alexandria-gfsc) [reply test/integration/graphql/partners_integration_test.rb:274]: It's up to you, and how much energy you have IMO. Like I think changing it would mean changing the whole file, but on the other hand `assert x == false` is generally an antipattern I think

**Review by kimadactyl — APPROVED** [review]
