### PR TITLE
Fix: cleaning up HTML before parsing into markdown

### LINKED ISSUE #1530: [Bug]: Metadata description for events is Markdown when it should be plain text
https://trans-dimension.placecal.org/events/320734:

Screenshot 2022-11-02 at 18 48 09

I think that says it all?

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #1530 

Strip HTML tags of their attributes (but keep <a> tag hrefs)

### CODE REVIEW

File: app/jobs/calendar_importer/events/base.rb [hunk 1]
```diff
@@ -52,10 +52,13 @@ def html_sanitize(input)
         # if we get HTML then remove all the attributes from all of
         # the tags so it doesn't interfere with the kramdown step
         doc.css('*').each do |tag|
+          # rubocop:disable Style/HashEachMethods
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/events/base.rb:55]: why not just to what rubocop asks instead? :)

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashEachMethods

**Comment by kimadactyl** [comment]
This looks good but prob as good a time as any to add at least a minimal test for this?

File: app/jobs/calendar_importer/events/base.rb (hunk 1 above)
Comment (ivan-kocienski-gfsc) [reply app/jobs/calendar_importer/events/base.rb:55]: Because it is assuming `tag` is an enumerable hash, which it is not, so invoking `each_key` raises a `NoMethodError`. It's just guessing based on text parsing and heuristics, which in this case is wrong

Comment (kimadactyl) [reply app/jobs/calendar_importer/events/base.rb:55]: fair, will leave this to F to sign off

**Review by kimadactyl — APPROVED** [review]
Looking good!
