### PR TITLE
Remove HTML from imported events

### LINKED ISSUE #1196: Remove HTML from imported event descriptions
**Describe the bug**

HTML from external sources is being directly added to PlaceCal which is confusing matters as we assume we're using markdown.

[Issue on TransDim](https://github.com/GenderedIntelligence/the-trans-dimension/issues/176#issuecomment-1096592250)

**To Reproduce**

1. Go to https://transdimension.netlify.app/events/232378

**Expected behavior**

Convert source HTML to markdown before saving it

**Screenshots**

image

### PR DESCRIPTION
**Pull request by ivankocienski**
Fixes #1196

### CODE REVIEW

File: app/jobs/calendar_importer/events/base.rb [hunk 1]
```diff
@@ -26,24 +26,24 @@ def sanitize_invalid_char(input)
...
+        doc << '<br/><br/>'
+        doc << footer
       end
 
-      str = str.to_s
+      body_text = doc.serialize
 
-      str = ActionController::Base.helpers.sanitize(str, tags: allowed_tags)
-      str = sanitize_invalid_char(str)
+      allowed_tags = %w[p a strong b em i ul ol li blockquote h3 h4 h5 h6 br]
```
Comment (kimadactyl) [inline app/jobs/calendar_importer/events/base.rb:43]: This feels like something we should have stored somewhere thats not hidden in a function. Maybe just move to a const?

**Comment by kimadactyl** [comment]
This looks really good but would like to see some more tests for different kinds of input. Maybe

- Something without proper closing tags
- Something with forbidden tags to check they get stripped
- Something with CSS classes to check they get stripped
- Markdown
- Anything else you can think of that people might fuck up somehow?
