### PR TITLE
Fix: scoping on site partners by tag

### LINKED ISSUE #1443: [Bug]: "Computer access" and "public wifi" are showing every partner
## Description

On the homepage for each site, every partner is showing up in the info sections

## Steps to reproduce

1. Go to https://hulme.placecal.org/
1. Note all partners are displayed

Screenshot 2022-09-05 at 13 44 36

## What you expected to happen

Only partners with the appropriate tags are displayed

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #1443 

A scope on partners that returns partners for a given site with a single (site) tag present. Partners can have either address OR service area in sites neighbourhoods

### CODE REVIEW

File: test/models/partner_site_with_tag_scope_test.rb [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+
+    neighbourhood = geocodable_neighbourhood_one
+    site.neighbourhoods << neighbourhood
+    site.tags << tag
+    site.tags << other_tag
+
+    4.times do |n|
+      partner = create(:partner, name: "Partner #{n}", address: address_one)
+      partner.tags << tag
+    end
```
Comment (kimadactyl) [inline test/models/partner_site_with_tag_scope_test.rb:61]: on a call about VAT and zoning out but maybe add in some partners with no tags too

**Review by aaaaargZombies — APPROVED** [review]
This works for me though I've spotted an issue with the links in the free wifi and computer access components that I'll write up

**Comment by kimadactyl** [comment]
Yeah this should also resolve #1452 and have tests for it

**Comment by aaaaargZombies** [comment]
my last commit should have fixed #1452

**Comment by kimadactyl** [comment]
looks good would just like a test to stop it happening again!

**Comment by kimadactyl** [comment]
Happy to merge this when you are!
