### PR TITLE
Bug: Events should not set their own address

### LINKED ISSUE #1244: [Bug]: Event strategy always prioritises Place.address if one is set
## Description

This is a hypothetical bug rather than one I can reproduce.

Aster noticed that this line means that if a place is set, it will always take precedence over the event location, even if event or override strategy is selected.

https://github.com/geeksforsocialchange/PlaceCal/blob/bbb664137d51b4bda26fb21f6495ca9961dffaba/app/models/event.rb#L158

If this is just a misunderstanding with interpretation then we need to improve the comment to show this.

## What you expected to happen

- [x] If event location is set and calendar strategy is 'event' or 'override', that location should be used instead of the partner's place
- [x] if event strategy is place, then it continues to work correctly
- [x] if event strategy is override and location is not set, it continues to work correctly

### PR DESCRIPTION
**Pull request by ivankocienski**
When an event is imported a factory is employed to give the event the
correct place/address. Therefore the event itself no longer has this
business logic in it

Fixes #1244

### CODE REVIEW

File: test/jobs/calendar_importer/event_resolver_strategy_test.rb [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+    # theory of test
+    #   given
+    #     data location is missing
+    #     calendar strategy is 'event_override'
+    #
+    #   then
+    #     event place = calendar place
+    #     event address = calendar place address
+
+    data = FakeEvent.new(
```
Comment (alexandria-gfsc) [inline test/jobs/calendar_importer/event_resolver_strategy_test.rb:164]: If you're using the same `data` for each test and only at most changing one or two values: I would put it into the setup and change that value on the struct in the test. This should just make it a little bit clearer that it is either the same structure, or mostly the same :)

Comment (ivankocienski) [reply test/jobs/calendar_importer/event_resolver_strategy_test.rb]: fixed

File: app/jobs/calendar_importer/event_resolver.rb [hunk 2]
```diff
@@ -118,7 +118,7 @@ def event_override_strategy(place, address: nil)
       if place.present?
         # place = 'calendar.place'
         # address = 'calendar.place.address'
-        place = calendar.place
+        # place = calendar.place
```
Comment (alexandria-gfsc) [inline app/jobs/calendar_importer/event_resolver.rb:121]: What's the reason for commenting out handling of `place` after checking whether it's present or not?

**Review by alexandria-gfsc — APPROVED** [review]
lgtm
