### PR TITLE
Fix: make importer JSON parsing more robust

### LINKED ISSUE #1491: Bug: JSON parsing error in Calendar Importer
[rollbar error](https://rollbar.com/gfsc/placecal-production/items/214/)

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #1491

### CODE REVIEW

File: app/jobs/calendar_importer/parsers/base.rb [hunk 1]
```diff
@@ -48,5 +48,11 @@ def calendar_to_events
     def digest(data)
       Digest::MD5.hexdigest(data.to_s)
     end
+
+    def safely_parse_json(string, default = nil)
+      JSON.parse string
```
Comment (katjam) [inline app/jobs/calendar_importer/parsers/base.rb:53]: I need a rails person to confirm, but should there be a `begin` before this line?

Comment (ivan-kocienski-gfsc) [reply app/jobs/calendar_importer/parsers/base.rb:53]: This is valid ruby. Methods can have `rescue` blocks at the end of them. There are tests covering this specific method in this PR

**Review by aaaaargZombies — APPROVED** [review]
looks good to me
